### ISSUE TITLE
cleanmarks() may take unnecessary code space

### ISSUE THREAD

**Issue by ampli** [pfalcon/re1.5#17]
cleanmarks() is used only in the pike and thompson functions.
However, it is defined in compilecode.c, and thus is included in programs that use only the recursiveloop function, like MicroPython (unless LTO is used, but this is another story):

```
$ nm micropython | grep cleanmark
00000000004f2aab T cleanmarks
```

This currently incurs (checked on x86_64) an unneeded code space overhead of 74 bytes, and 102 bytes after the fix needed for #16 (and even some more space after **{n,m}** is added).

In order to solve that, I propose to do the following:
1. Move cleanmarks() it to pike.c.
2. As I propose in #9, **remove** thompson.c - since it is merely pike.c without the sub captures,
and add a comment that says so in pike.c.

**Comment by pfalcon** [comment]
Common sense says that it should go to to its own module then ;-). I'd do that change, but don't want to cause possible conflicts with your changes, let me know if you'd want me to proceed with it.

**Comment by ampli** [comment]
Yes, please do that. I guess you can even fix the indentation when doing so, saving me a pull request for that.
If you do that now I will just be able to "git pull" and proceed with my changes.

**Comment by pfalcon** [comment]
Done. Closing this then!
